# Generated by Django 3.1.5 on 2021-01-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_employee', models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('reporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/')),
                ('employee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subord')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('time_of_action', models.DateTimeField(auto_now_add=True)),
                ('images_to_upload', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=30)),
                ('reporter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reporter')),
            ],
        ),
    ]
